from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
import datetime
import os

# Helper shortcut
def p(text):
    return Paragraph(text, ParagraphStyle('body', fontSize=10, leading=14))


def add_header_footer(canvas, doc):
    canvas.saveState()

    # --- TITLE ---
    canvas.setFont('Helvetica-Bold', 18)
    title_y = doc.height + doc.topMargin - 10
    canvas.drawString(50, title_y, "OncoSim Clinical Report")

    # --- TIME UNDER TITLE ---
    canvas.setFont("Helvetica", 9)
    date_y = title_y - 12
    now_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    canvas.drawString(50, date_y, now_str)

    # --- LOGO RIGHT ---
    logo_path = "logo.png"
    if os.path.exists(logo_path):
        canvas.drawImage(
            logo_path,
            doc.leftMargin + doc.width - 80,
            doc.height + doc.topMargin - 40,
            width=60,
            height=60,
            preserveAspectRatio=True,
            mask='auto'
        )

    # --- HORIZONTAL LINE UNDER TIME ---
    line_y = date_y - 10
    canvas.line(50, line_y, doc.leftMargin + doc.width - 50, line_y)

    # -------------------------------
    # PATIENT INFO UNDER THE LINE
    # -------------------------------
    patient_y = line_y - 12
    # Patient Name (LEFT)
    canvas.setFont("Helvetica", 9)
    canvas.drawString(50, patient_y, f"Patient: {getattr(canvas, 'patient_name', 'Anonymous')}")
    # Report Date (RIGHT)
    report_date = datetime.datetime.now().strftime("%Y-%m-%d")
    canvas.drawRightString(
        doc.leftMargin + doc.width - 50,
        patient_y,
        f"Report Date: {report_date}"
    )

    # --- FOOTER ---
    canvas.setFont('Helvetica-Oblique', 8)
    canvas.setFillColor(colors.gray)
    canvas.drawCentredString(
        doc.width/2 + doc.leftMargin,
        30,
        f"Page {doc.page} | Confidential | Generated by OncoSim AI"
    )

    canvas.restoreState()


def generate_pdf_report(filepath, data):
    # MARGINS SAME AS YOUR ORIGINAL WORKING VERSION
    doc = SimpleDocTemplate(
        filepath,
        pagesize=letter,
        topMargin=108,
        bottomMargin=36,
        leftMargin=50,
        rightMargin=50
    )

    story = []
    styles = getSampleStyleSheet()

    style_h2 = ParagraphStyle(
        name='H2',
        parent=styles['h2'],
        fontSize=16,
        spaceBefore=10,
        spaceAfter=8,
        textColor=colors.darkblue
    )

    style_body = styles['BodyText']
    style_body.leading = 14

    # --------------------
    # VISUAL OVERVIEW
    # --------------------
    if 'raw_image' in data:
        story.append(Paragraph("<b>Visual Overview</b>", style_h2))

        img_data = [
            [p("<b>Pre-Op Scan</b>"), p("<b>AI Segmentation</b>"), p("<b>Thermal State</b>")],
            [
                Image(data['raw_image'], width=150, height=150),
                Image(data['seg_image'], width=150, height=150),
                Image(data['heat_image'], width=150, height=150)
            ]
        ]

        tbl_images = Table(img_data, colWidths=[166,166,166])
        tbl_images.setStyle(TableStyle([
            ('ALIGN',(0,0),(-1,-1),'CENTER'),
            ('VALIGN',(0,0),(-1,-1),'MIDDLE')
        ]))

        story.append(tbl_images)
        story.append(Spacer(1, 20))

    # --------------------
    # DIAGNOSIS
    # --------------------
    if 'tumor_type' in data:

        story.append(Paragraph("1. Pathology & Diagnosis", style_h2))

        diag_data = [
            [p("<b>Classification:</b>"), p(data.get('tumor_type', '-')), p("<b>Location:</b>"), p(data.get('location_ai', '-'))],
            [p("<b>Grade:</b>"), p(data.get('grade', '-')), p("<b>Depth:</b>"), p(data.get('depth', '-'))],
            [p("<b>Max Diameter:</b>"), p(str(data.get('size', '-')) + ' mm'), p("<b>Area:</b>"), p(data.get('area', '-'))],
            [p("<b>Dimensions:</b>"), p(data.get('dims', '-')), p("<b>Shape:</b>"), p(data.get('shape', '-'))],
            [p("<b>Centroid (px):</b>"), p(data.get('location', '-'))]
        ]

        tbl_diag = Table(diag_data, hAlign='LEFT')
        story.append(tbl_diag)
        story.append(Spacer(1, 15))

        story.append(Paragraph(f"<b>Pathology Analysis:</b> {data.get('pathology','-')}", style_body))
        story.append(Spacer(1,10))
        story.append(Paragraph(
            f"<font color='red'><b>AI Recommendation:</b> {data.get('recommendation','-')}</font>",
            style_body)
        )
        story.append(Spacer(1,25))

    # --------------------
    # PHYSICS (EXACT FORMAT YOU PROVIDED)
    # --------------------
    if 'power' in data:
        story.append(Paragraph("2. Ablation Physics", style_h2))

        phys_data = [
            [p("<b>Power:</b>"), p(f"{data.get('power')} W"),
             p("<b>Mode:</b>"), p(data.get('mode'))],

            [p("<b>Energy:</b>"), p(f"{data.get('energy')} J"),
             p("<b>Source:</b>"), p(data.get('material'))],

            [p("<b>Target ΔT:</b>"), p(f"+{data.get('target_temp')} °C"),
             p("<b>Pulse Width:</b>"),
             p(f"{data.get('pulse_width')} ms" if data.get('pulse_width') else 'N/A')],

            [p("<b>Duration:</b>"), p(f"{data.get('total_duration')} s"), "", ""],
        ]

        tbl_phys = Table(phys_data, hAlign='LEFT')
        story.append(tbl_phys)
        story.append(Spacer(1,25))

    # --------------------
    # NEW: GROWTH SIMULATION SECTION
    # --------------------
    if 'growth_sim_image' in data:
        story.append(Paragraph("3. Predicted Tumor Growth", style_h2))

        gp = data.get('growth_params', {})

        # --- FIX: Use the blended image and add Growth Delta ---
        if os.path.exists(data['growth_sim_image']):
            # Image in the middle
            story.append(Image(data['growth_sim_image'], width=150, height=150))

        story.append(Spacer(1, 15))
        # ----------------------------------------------------

        # Parameters Table with merged cell for "Final Growth"
        growth_data = [
            # Row 1
            [p("<b>Diffusion (D):</b>"), p(str(gp.get('D', '-'))),
             p("<b>Proliferation (ρ):</b>"), p(str(gp.get('rho', '-')))],

            # Row 2
            [p("<b>Necrosis (β):</b>"), p(str(gp.get('beta', '-'))),
             p("<b>Duration:</b>"), p(f"{gp.get('duration', '-')} {gp.get('time_scale', '')}")],

            # Row 3 (New, spans last three columns)
            [p("<b>Final Growth:</b>"), p(gp.get('growth_delta', 'N/A')), "", ""]
        ]

        tbl_growth = Table(growth_data, hAlign='LEFT', colWidths=[100, 150, 100, 150])

        # Style to merge cells for the last row
        tbl_growth.setStyle(TableStyle([
            ('SPAN', (1, 2), (3, 2)), # Span from col 1 to col 3 on row 2
        ]))

        story.append(tbl_growth)
        story.append(Spacer(1, 25))

    # --------------------
    # CHAT LOG (Now Section 4)
    # --------------------
    if 'chat_history' in data and data['chat_history']:
        story.append(Paragraph("4. AI Consultation Log", style_h2))

        for msg in data['chat_history']:
            role = msg.get("role", "unknown").capitalize()
            content = msg.get("content", "").replace("\n", "<br/>")

            if role == "User":
                story.append(Paragraph(f"<b>You:</b> {content}", style_body))
            else:
                story.append(Paragraph(f"<b>Dr. AI:</b> {content}", style_body))

            story.append(Spacer(1, 8))

    # --------------------
    # BUILD PDF, with patient name in the header
    # --------------------

    # Store patient name for header rendering
    def add_header_wrapper(canvas, doc):
        canvas.patient_name = data.get("patient_name", "Anonymous")
        add_header_footer(canvas, doc)

    doc.build(
        story,
        onFirstPage=add_header_wrapper,
        onLaterPages=add_header_wrapper
    )

    return True